version: "3.8"
services:
    wordpress:
        build:
            dockerfile: Dockerfile
            context: ./wordpress
        ports: 
            - 9000:80
        volumes:
            - wordpress:/var/lib/wordpress
        depends_on: 
            - mysql
            - nginx
        networks:
            - cluster
    mysql:
        build:
            dockerfile: Dockerfile
            context: ./mysql
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: password
        restart: always
        networks:
            - cluster
    nginx:
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports: 
            - 443:433
        networks:
            - cluster
networks:
    cluster:
        driver: bridge
volumes:
    mysql:
    wordpress:


