version: '3'

services:
  mariadb:
    build:
      context: ./mariadb
      args:
        - MYSQL_ROOT=${MYSQL_ROOT}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: always
    container_name: mariadb
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - cluster
  nginx:
    build: ./nginx/
    restart: always
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - cluster
    ports:
      - 443:443
      - 80:80
    depends_on:
      - wordpress
  wordpress:
    build: ./wordpress/
    container_name: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    environment:
      - MYSQL_HOST=mariadb
    networks:
      - cluster
    depends_on:
      - mariadb

volumes:
  wordpress:
  dbdata:

networks:
    cluster:
