version: '3'

services:
  mariadb:
    build: ./mariadb
    restart: always
    container_name: mariadb
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - cluster
  nginx:
    build: ./nginx/
    restart: always
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - cluster
    ports:
      - 443:443
      - 80:80
    depends_on:
      - wordpress
  wordpress:
    build: ./wordpress/
    container_name: wordpress
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    environment:
      - DB_HOST=mariadb
      - DB_USER=$MYSQL_USER
      - DB_PASSWORD=$MYSQL_PASSWORD
      - DB_DATABASE=$MYSQL_DATABASE
      - INTRANAME=$INTRANAME
    networks:
      - cluster
    depends_on:
      - mariadb

volumes:
  wordpress:
  dbdata:

networks:
    cluster:
