version: '3'

services:
  mariadb:
    build:
      dockerfile: Dockerfile
      context: ./mariadb
    restart: unless-stopped
    tty: true
    expose:
      - 3306
    volumes:
      - ~/data/mariadb:/var/lib/mysql
    networks:
      - app-network
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ~/data/static:/static/
    networks:
      - app-network
    expose:
      - 443
    depends_on:
      - wordpress
  wordpress:
    build:
      dockerfile: Dockerfile
      context: ./wordpress
    restart: unless-stopped
    tty: true
    volumes:
      - ~/data/static:/static/
    networks:
      - app-network
    expose:
      - 9000
    depends_on:
      - mariadb

networks:
  app-network:
    driver: bridge
