FROM debian:buster
RUN apt-get update && apt-get upgrade && apt-get install -y wordpress php7.3 php7.3-fpm php7.3-curl php7.3-json php7.3-mysql wget
ADD ./ ./srcs/
EXPOSE 9000
CMD ["bash", "/srcs/start.sh"]